"""The sky, the sun and the moon, authored into the session layer.

Everything this writes lives under ``/WeatherFX`` in the **session layer**, so a user's own stage
is never modified and ``detach`` really does undo it. That is the same rule the fog and
precipitation effects follow, and it is the reason this extension can be switched on over someone
else's scene without asking them to save anything.

What it authors:

* a ``UsdLux.DomeLight`` bound to a latitude-longitude EXR generated by
  :func:`weather_fx.core.sky.environment_map`, visible to primary rays so the sky is *seen* and
  not merely lit by;
* a ``UsdLux.DistantLight`` for the sun, aimed along the NOAA direction, at the sun's real
  angular diameter so contact shadows have the right softness;
* a second ``DistantLight`` for the moon, aimed and scaled by the same machinery. It is not
  decoration: a night scene lit only by a dome has no shadows at all, and the moon casts sharp
  ones.

**The bake is the expensive part and it is cached.** Regenerating a 1024-row map costs a few
seconds, most of it the cloud march, so the effect keeps the inputs it baked at and only rebuilds
when something that changes the sky actually changes. Scrubbing a slider that the sky does not
depend on costs nothing.

**Stage axes.** A dome light's texture is oriented by the stage's own axes, and the sun direction
has to be expressed in them too. Both are handled through ``WeatherContext.up_axis``: the
generated map is authored in the Y-up convention the renderer's lat-long layout assumes, and a
Z-up stage gets the dome rotated rather than the map regenerated, because rotating a light is
exact and resampling a texture is not.
"""
from __future__ import annotations

import hashlib
import logging
import math
import os
import pathlib
import tempfile
from typing import Any, Optional, Set

from ...core.meteorology import beam_tint, clear_sky_irradiance
from ...core.sky import (
    SkyConditions,
    dome_exposure,
    conditions_from_state,
    environment_map,
)
from ...core.clouds import CLOUD_SHAPE_KEYS
from ...core.jobs import LatestJob
from ..base import Effect
from .render_mode import RenderModeWatcher, cloud_path
from .scene_lights import SceneLightSuppressor

log = logging.getLogger("weather_fx")

SKY_ROOT = "/WeatherFX/Sky"
DOME_PATH = f"{SKY_ROOT}/Dome"
SUN_PATH = f"{SKY_ROOT}/Sun"
MOON_PATH = f"{SKY_ROOT}/Moon"

#: Luminous efficacy of daylight, lm/W. Converts the sun's irradiance into the photometric units
#: a `DistantLight` intensity is quoted in.
LUMINOUS_EFFICACY_DAYLIGHT = 105.0



class SkyEffect(Effect):
    """Authors the environment dome, the sun and the moon from the ``sky`` state section."""

    name = "sky"

    #: Which parameters the baked texture depends on. A change to anything else -- the sun's
    #: intensity scale, say -- re-aims the lights without paying for a rebake.
    _BAKE_KEYS = (
        ("sky", ("model", "horizon_blend_deg", "latitude_deg", "longitude_deg", "date_utc",
                 "hour_utc", "turbidity", "ground_albedo", "star_intensity", "dome_resolution")),
    )
    #: Cloud parameters the dome depends on -- only when the clouds are painted into it. Under the
    #: path tracer they are volumes and the dome is clear sky, so a cloud edit costs it nothing.
    _DOME_CLOUD_KEYS = CLOUD_SHAPE_KEYS + ("march_steps", "lit_color", "shadow_color", "dome_rows")
    #: Rows of the quick clear-sky bake put up the first time, so the dome is never untextured
    #: (a dome light with no texture is a uniform white light) while the real one is baking.
    _FIRST_BAKE_ROWS = 256

    def __init__(self, texture_dir: Optional[str] = None):
        self._texture_dir = pathlib.Path(texture_dir) if texture_dir else None
        self._baked_key: Optional[str] = None
        self._texture_path: Optional[pathlib.Path] = None
        self._conditions: Optional[SkyConditions] = None
        self._authored = False
        self._exposure = 1.0
        self._scene_lights = SceneLightSuppressor()
        self._job = LatestJob("weather_fx-sky")
        self._watcher: Optional[RenderModeWatcher] = None
        self._baked_conditions: Optional[SkyConditions] = None

    def attach(self, context) -> None:
        super().attach(context)
        self._watcher = RenderModeWatcher()

    # --- lifecycle ---------------------------------------------------------------------

    def apply_state(self, state: Any, changed: Set[str]) -> None:
        stage = self.context.stage()
        if stage is None:
            return
        if not (state.general.enabled and state.sky.enabled):
            self.detach()
            return
        if self._authored and not ({"sky", "clouds", "general"} & set(changed)):
            return

        path = cloud_path(state)
        key = self._bake_key(state, path)
        rebake = key != self._baked_key
        if rebake and key != self._job.running_key:
            snapshot = state.copy()
            directory = self._texture_dir or pathlib.Path(tempfile.gettempdir())

            def bake():
                return _bake(snapshot, key, path, directory)

            if state.general.time_source == "manual":
                # Deterministic runs get the sky their state describes on this very frame.
                self._job.cancel()
                self._install_bake(bake())
            else:
                if self._texture_path is None:
                    self._install_bake(_bake(snapshot, key + "-first", "volume", directory,
                                             rows=self._FIRST_BAKE_ROWS))
                self._job.submit(key, bake)
        # The sun and the moon are cheap and move now; only the dome texture waits for its bake.
        self._conditions = conditions_from_state(state, build_cloud=False)
        self._author(stage, state, self._conditions)
        self._authored = True
        if state.sky.hide_scene_lights:
            # A change to the sky section itself is the moment to catch lights added since.
            self._scene_lights.suppress(stage, rescan="sky" in changed and rebake)
        else:
            self._scene_lights.restore()

    def update(self, dt: float, t: float) -> None:
        self._poll_bake()
        self._advance_clock(dt)

    def _poll_bake(self) -> None:
        if self._watcher is not None and self._watcher.changed() and self._authored:
            self.apply_state(self.context.state, {"clouds"})
        try:
            done = self._job.poll()
        except Exception:
            log.exception("weather_fx: baking the sky failed")
            return
        if done is None:
            return
        _, result = done
        stage = self.context.stage()
        if stage is None or not self._authored:
            _unlink(result["texture"])
            return
        self._install_bake(result)
        state = self.context.state
        if self._conditions is not None:
            self._author(stage, state, self._conditions)

    def _install_bake(self, result: dict) -> None:
        previous = self._texture_path
        self._texture_path = result["texture"]
        self._exposure = result["exposure"]
        self._baked_key = result["key"]
        self._baked_conditions = result["conditions"]
        if previous is not None and previous != self._texture_path:
            # The renderer may still hold the old one; a temp file is the OS's problem after that.
            _unlink(previous)

    def _advance_clock(self, dt: float) -> None:
        """Advance the clock, if the state asks for it.

        Deliberately *not* a rebake every frame: the sky is written back into the state's own
        ``hour_utc`` and the manager's diff decides whether anything has to be regenerated. So a
        scene whose sun is moving slowly rebakes when the sun has actually moved, and one whose
        clock is held costs nothing at all.
        """
        state = self.context.state
        if not (state.general.enabled and state.sky.enabled and state.sky.advance_clock):
            return
        hours = dt * state.general.time_scale / 3600.0
        if hours <= 0.0:
            return
        state.sky.hour_utc = (state.sky.hour_utc + hours) % 24.0

    def detach(self) -> None:
        try:
            self._scene_lights.restore()
        except Exception:
            log.exception("weather_fx: could not restore the scene lights")
        stage = self.context.stage() if hasattr(self, "context") else None
        if stage is not None:
            try:
                from pxr import Usd

                with Usd.EditContext(stage, stage.GetSessionLayer()):
                    if stage.GetPrimAtPath(SKY_ROOT):
                        stage.RemovePrim(SKY_ROOT)
            except Exception:
                log.exception("weather_fx: could not remove the sky prims")
        self._authored = False
        self._baked_key = None
        self._job.cancel()
        if self._texture_path is not None:
            _unlink(self._texture_path)
            self._texture_path = None

    def stats(self) -> dict:
        if self._conditions is None:
            return {"authored": False}
        conditions = self._conditions
        return {
            "authored": self._authored,
            "scene_lights_hidden": self._scene_lights.hidden_count,
            "utc": conditions.when.isoformat(),
            "sun_elevation_deg": round(conditions.sun.elevation_deg, 2),
            "sun_azimuth_deg": round(conditions.sun.azimuth_deg, 2),
            "moon_elevation_deg": round(conditions.moon.elevation_deg, 2),
            "moon_phase": conditions.moon.phase_name,
            "moon_lux": round(conditions.moon_lux, 4),
            "daylight": round(conditions.daylight, 4),
            "cloud_cover_in_dome": (
                round(self._baked_conditions.cloud.measured_cover, 3)
                if self._baked_conditions is not None and self._baked_conditions.cloud else 0.0
            ),
            "baking": self._job.busy,
            "texture": str(self._texture_path) if self._texture_path else None,
        }

    # --- the bake ------------------------------------------------------------------------

    def _bake_key(self, state: Any, path: str) -> str:
        parts = [f"path={path}"]
        for section, names in self._BAKE_KEYS:
            block = getattr(state, section)
            parts.extend(f"{section}.{n}={getattr(block, n)!r}" for n in names)
        if path == "dome" and state.clouds.enabled:
            parts.extend(f"clouds.{n}={getattr(state.clouds, n)!r}" for n in self._DOME_CLOUD_KEYS)
        return hashlib.sha1("|".join(parts).encode("utf-8")).hexdigest()

    # --- authoring -----------------------------------------------------------------------

    def _author(self, stage: Any, state: Any, conditions: SkyConditions) -> None:
        from pxr import Gf, Sdf, Usd, UsdGeom, UsdLux

        up_axis = self.context.up_axis()
        sky = state.sky
        scale = float(sky.exposure_scale)

        # The beam's colour, split into a light colour (peak-normalised, because a `UsdLux` colour
        # is a multiplier and a channel above one is a surprise waiting in somebody's shader) and
        # the factor that puts back what the normalisation took. The product is unchanged, so the
        # light is exactly as bright as the irradiance says and exactly as orange as the airmass
        # says. Without this a scene at a four-degree sun is merely dim, which is the one thing a
        # sunset is not.
        sun_tint = beam_tint(conditions.sun.elevation_deg, conditions.turbidity)
        sun_peak = max(sun_tint) or 1.0
        moon_tint = tuple(
            a * b for a, b in zip(beam_tint(conditions.moon.elevation_deg, conditions.turbidity),
                                  (0.84, 0.90, 1.0))
        )
        moon_peak = max(moon_tint) or 1.0

        with Usd.EditContext(stage, stage.GetSessionLayer()):
            stage.DefinePrim("/WeatherFX", "Xform")
            stage.DefinePrim(SKY_ROOT, "Xform")

            dome = UsdLux.DomeLight.Define(stage, DOME_PATH)
            if self._texture_path is not None:
                dome.CreateTextureFileAttr().Set(Sdf.AssetPath(str(self._texture_path)))
                dome.CreateTextureFormatAttr().Set(UsdLux.Tokens.latlong)
            dome.CreateIntensityAttr(self._exposure * scale)
            # The sun and the moon are exposed by the *same* factor as the dome below. They are
            # quoted in lux and the dome's texture in cd/m2, so leaving the lights unexposed puts
            # the sun some two and a half decades above the sky it shares a frame with: the sky
            # renders correctly and every surface the sun touches clips to white. A sunlit 0.19
            # albedo ground and a clear zenith belong within a stop of each other, which is what
            # one exposure gives and two cannot.
            # RTX hides a dome from primary rays unless told otherwise, which gives a black
            # background lit by a sky nobody can see -- the exact failure this module fixes.
            dome.GetPrim().CreateAttribute(
                "visibleInPrimaryRay", Sdf.ValueTypeNames.Bool
            ).Set(True)
            self._orient_dome(dome, up_axis)

            self._author_body(
                stage,
                SUN_PATH,
                conditions.sun,
                up_axis,
                enabled=bool(sky.sun_enabled) and conditions.sun.is_up,
                intensity=(
                    float(
                        clear_sky_irradiance(
                            conditions.sun.elevation_deg, conditions.turbidity
                        )[0]
                    )
                    * LUMINOUS_EFFICACY_DAYLIGHT
                    * conditions.daylight
                    * self._exposure
                    * scale
                    * sun_peak
                ),
                colour=tuple(c / sun_peak for c in sun_tint),
            )
            self._author_body(
                stage,
                MOON_PATH,
                conditions.moon,
                up_axis,
                enabled=bool(sky.moon_enabled) and conditions.moon.is_up,
                # The moon's normal illuminance, from the horizontal one it produces.
                intensity=(
                    conditions.moon_lux
                    / max(math.sin(math.radians(max(conditions.moon.elevation_deg, 1.0))), 1e-3)
                    * self._exposure
                    * scale
                    * moon_peak
                ),
                colour=tuple(c / moon_peak for c in moon_tint),
            )

    @staticmethod
    def _orient_dome(dome: Any, up_axis: int) -> None:
        """Rotate the dome for a Z-up stage rather than regenerating its texture.

        The map is generated in the renderer's lat-long convention for a Y-up stage. Rotating a
        light is exact; resampling an environment map is not, and it would also mean two code
        paths producing two slightly different skies.
        """
        from pxr import Gf, UsdGeom

        xform = UsdGeom.Xformable(dome)
        xform.ClearXformOpOrder()
        if up_axis == 2:
            xform.AddRotateXOp().Set(90.0)

    @staticmethod
    def _author_body(
        stage: Any,
        path: str,
        body: Any,
        up_axis: int,
        *,
        enabled: bool,
        intensity: float,
        colour: tuple,
    ) -> None:
        from pxr import Gf, UsdGeom, UsdLux

        light = UsdLux.DistantLight.Define(stage, path)
        prim = light.GetPrim()
        if not enabled or intensity <= 0.0:
            UsdGeom.Imageable(prim).MakeInvisible()
            light.CreateIntensityAttr(0.0)
            return
        UsdGeom.Imageable(prim).MakeVisible()

        north_axis, north_sign = (2, -1.0) if up_axis == 1 else (1, 1.0)
        toward = body.direction(up_axis=up_axis, north_axis=north_axis, north_sign=north_sign)
        # A distant light emits along its own -Z, so -Z must point the way the light travels --
        # which is *away* from the body.
        rotation = Gf.Rotation(Gf.Vec3d(0.0, 0.0, -1.0), Gf.Vec3d(*(-float(v) for v in toward)))
        xform = UsdGeom.Xformable(prim)
        xform.ClearXformOpOrder()
        xform.AddOrientOp().Set(Gf.Quatf(rotation.GetQuat()))

        light.CreateIntensityAttr(float(intensity))
        light.CreateAngleAttr(float(body.angular_diameter_deg))
        light.CreateColorAttr(Gf.Vec3f(*colour))


def _unlink(path: Any) -> None:
    try:
        pathlib.Path(path).unlink()
    except OSError:
        log.debug("weather_fx: could not remove the sky texture %s", path)


def _bake(state: Any, key: str, path: str, directory: pathlib.Path, rows: Optional[int] = None) -> dict:
    """Bake the dome texture. Runs in a worker thread, so it touches nothing but its arguments.

    The dome's *intensity* carries the exposure and the texture stays in honest cd/m2: the sky's
    level moves by seven decades between noon and a moonless night and no fixed intensity survives
    that. The rule lives in `core.sky.dome_exposure` so it can be tested without a renderer.

    **One file per bake.** The renderer caches a texture by its path, so reusing one served every
    later sky the first one's pixels, and overwriting a file the loader was still reading produced
    "Unexpected data block y coordinate" from OpenEXR. The pid keeps processes apart and the bake
    key keeps skies apart.
    """
    from ...core.exr import write_exr

    conditions = conditions_from_state(state, build_cloud=(path == "dome"))
    image = environment_map(conditions, height=int(rows or state.sky.dome_resolution))
    directory.mkdir(parents=True, exist_ok=True)
    texture = directory / f"weather_fx_sky_{os.getpid()}_{key[:18]}.exr"
    write_exr(texture, image)
    return {"texture": texture, "exposure": dome_exposure(image), "key": key,
            "conditions": conditions}
