"""The sky, the sun and the moon, authored into the session layer.

Everything this writes lives under ``/WeatherFX`` in the **session layer**, so a user's own stage
is never modified and ``detach`` really does undo it. That is the same rule the fog and
precipitation effects follow, and it is the reason this extension can be switched on over someone
else's scene without asking them to save anything.

What it authors:

* a ``UsdLux.DomeLight`` bound to a latitude-longitude EXR generated by
  :func:`weather_fx.core.sky.environment_map`, visible to primary rays so the sky is *seen* and
  not merely lit by;
* a ``UsdLux.DistantLight`` for the sun, aimed along the NOAA direction, at the sun's real
  angular diameter so contact shadows have the right softness;
* a second ``DistantLight`` for the moon, aimed and scaled by the same machinery. It is not
  decoration: a night scene lit only by a dome has no shadows at all, and the moon casts sharp
  ones.

**The bake is the expensive part and it is cached.** Regenerating a 1024-row map costs a few
seconds, most of it the cloud march, so the effect keeps the inputs it baked at and only rebuilds
when something that changes the sky actually changes. Scrubbing a slider that the sky does not
depend on costs nothing.

**Stage axes.** A dome light's texture is oriented by the stage's own axes, and the sun direction
has to be expressed in them too. Both are handled through ``WeatherContext.up_axis``: the
generated map is authored in the Y-up convention the renderer's lat-long layout assumes, and a
Z-up stage gets the dome rotated rather than the map regenerated, because rotating a light is
exact and resampling a texture is not.
"""
from __future__ import annotations

import hashlib
import logging
import math
import os
import pathlib
import tempfile
from typing import Any, Optional, Set

from ...core.meteorology import beam_tint, clear_sky_irradiance
from ...core.sky import (
    SkyConditions,
    dome_exposure,
    conditions_from_state,
    environment_map,
)
from ..base import Effect

log = logging.getLogger("weather_fx")

SKY_ROOT = "/WeatherFX/Sky"
DOME_PATH = f"{SKY_ROOT}/Dome"
SUN_PATH = f"{SKY_ROOT}/Sun"
MOON_PATH = f"{SKY_ROOT}/Moon"

#: Luminous efficacy of daylight, lm/W. Converts the sun's irradiance into the photometric units
#: a `DistantLight` intensity is quoted in.
LUMINOUS_EFFICACY_DAYLIGHT = 105.0



class SkyEffect(Effect):
    """Authors the environment dome, the sun and the moon from the ``sky`` state section."""

    name = "sky"

    #: Which parameters the baked texture depends on. A change to anything else -- the sun's
    #: intensity scale, say -- re-aims the lights without paying for a rebake.
    _BAKE_KEYS = (
        ("sky", ("latitude_deg", "longitude_deg", "date_utc", "hour_utc", "turbidity",
                 "ground_albedo", "star_intensity", "dome_resolution")),
        ("clouds", ("enabled", "cover", "genus", "base_m", "temperature_c", "dewpoint_c",
                    "thickness_m", "optical_depth", "feature_m", "cells", "levels", "cell_m",
                    "seed", "march_steps")),
    )

    def __init__(self, texture_dir: Optional[str] = None):
        self._texture_dir = pathlib.Path(texture_dir) if texture_dir else None
        self._baked_key: Optional[str] = None
        self._texture_path: Optional[pathlib.Path] = None
        self._conditions: Optional[SkyConditions] = None
        self._authored = False
        self._exposure = 1.0

    # --- lifecycle ---------------------------------------------------------------------

    def apply_state(self, state: Any, changed: Set[str]) -> None:
        stage = self.context.stage()
        if stage is None:
            return
        if not (state.general.enabled and state.sky.enabled):
            self.detach()
            return
        if self._authored and not ({"sky", "clouds", "general"} & set(changed)):
            return

        key = self._bake_key(state)
        rebake = key != self._baked_key or self._texture_path is None
        if rebake:
            self._conditions = conditions_from_state(state)
            self._bake(state, key)
            self._baked_key = key
        assert self._conditions is not None
        self._author(stage, state, self._conditions)
        self._authored = True

    def update(self, dt: float, t: float) -> None:
        """Advance the clock, if the state asks for it.

        Deliberately *not* a rebake every frame: the sky is written back into the state's own
        ``hour_utc`` and the manager's diff decides whether anything has to be regenerated. So a
        scene whose sun is moving slowly rebakes when the sun has actually moved, and one whose
        clock is held costs nothing at all.
        """
        state = self.context.state
        if not (state.general.enabled and state.sky.enabled and state.sky.advance_clock):
            return
        hours = dt * state.general.time_scale / 3600.0
        if hours <= 0.0:
            return
        state.sky.hour_utc = (state.sky.hour_utc + hours) % 24.0

    def detach(self) -> None:
        stage = self.context.stage() if hasattr(self, "context") else None
        if stage is not None:
            try:
                from pxr import Usd

                with Usd.EditContext(stage, stage.GetSessionLayer()):
                    if stage.GetPrimAtPath(SKY_ROOT):
                        stage.RemovePrim(SKY_ROOT)
            except Exception:
                log.exception("weather_fx: could not remove the sky prims")
        self._authored = False
        self._baked_key = None

    def stats(self) -> dict:
        if self._conditions is None:
            return {"authored": False}
        conditions = self._conditions
        return {
            "authored": self._authored,
            "utc": conditions.when.isoformat(),
            "sun_elevation_deg": round(conditions.sun.elevation_deg, 2),
            "sun_azimuth_deg": round(conditions.sun.azimuth_deg, 2),
            "moon_elevation_deg": round(conditions.moon.elevation_deg, 2),
            "moon_phase": conditions.moon.phase_name,
            "moon_lux": round(conditions.moon_lux, 4),
            "daylight": round(conditions.daylight, 4),
            "cloud_cover": (
                round(conditions.cloud.measured_cover, 3) if conditions.cloud else 0.0
            ),
            "texture": str(self._texture_path) if self._texture_path else None,
        }

    # --- the bake ------------------------------------------------------------------------

    def _bake_key(self, state: Any) -> str:
        parts = []
        for section, names in self._BAKE_KEYS:
            block = getattr(state, section)
            parts.extend(f"{section}.{n}={getattr(block, n)!r}" for n in names)
        return hashlib.sha1("|".join(parts).encode("utf-8")).hexdigest()

    def _bake(self, state: Any, key: str = "") -> None:
        from ...core.exr import write_exr

        assert self._conditions is not None
        height = int(state.sky.dome_resolution)
        image = environment_map(self._conditions, height=height)

        # The dome's *intensity* carries the exposure and the texture stays in honest cd/m2. The
        # sky's absolute level moves by seven decades between noon and a moonless night, and no
        # fixed intensity survives that: one end of the day is blown out and the other is black.
        # The rule lives in `core.sky.dome_exposure` so it can be tested without a renderer.
        self._exposure = dome_exposure(image)

        directory = self._texture_dir or pathlib.Path(tempfile.gettempdir())
        directory.mkdir(parents=True, exist_ok=True)
        # **One file per bake, not one per process.** Writing every sky to the same path looks
        # tidy and breaks two ways at once: the renderer caches a texture by its path, so the
        # second sky of a session is served the first one's pixels, and overwriting a file the
        # loader may still be reading produces "Unexpected data block y coordinate" from
        # OpenEXR -- a half-written file, read as a whole one. Both were live until this was
        # measured: a scenario sweep rendered thirteen different skies as one.
        #
        # The pid keeps two processes on a shared machine apart; the bake key keeps two skies
        # within one process apart, and makes the name reproducible for the same conditions.
        previous = self._texture_path
        digest = key or self._bake_key(state)
        path = directory / f"weather_fx_sky_{os.getpid()}_{digest[:12]}.exr"
        write_exr(path, image)
        self._texture_path = path
        if previous is not None and previous != path:
            # The renderer may still hold the old one; a failure to remove it is not worth a
            # broken sky, and a temp file is the operating system's problem after that.
            try:
                previous.unlink()
            except OSError:
                log.debug("weather_fx: could not remove the previous sky texture %s", previous)

    # --- authoring -----------------------------------------------------------------------

    def _author(self, stage: Any, state: Any, conditions: SkyConditions) -> None:
        from pxr import Gf, Sdf, Usd, UsdGeom, UsdLux

        up_axis = self.context.up_axis()
        sky = state.sky
        scale = float(sky.exposure_scale)

        # The beam's colour, split into a light colour (peak-normalised, because a `UsdLux` colour
        # is a multiplier and a channel above one is a surprise waiting in somebody's shader) and
        # the factor that puts back what the normalisation took. The product is unchanged, so the
        # light is exactly as bright as the irradiance says and exactly as orange as the airmass
        # says. Without this a scene at a four-degree sun is merely dim, which is the one thing a
        # sunset is not.
        sun_tint = beam_tint(conditions.sun.elevation_deg, conditions.turbidity)
        sun_peak = max(sun_tint) or 1.0
        moon_tint = tuple(
            a * b for a, b in zip(beam_tint(conditions.moon.elevation_deg, conditions.turbidity),
                                  (0.84, 0.90, 1.0))
        )
        moon_peak = max(moon_tint) or 1.0

        with Usd.EditContext(stage, stage.GetSessionLayer()):
            stage.DefinePrim("/WeatherFX", "Xform")
            stage.DefinePrim(SKY_ROOT, "Xform")

            dome = UsdLux.DomeLight.Define(stage, DOME_PATH)
            if self._texture_path is not None:
                dome.CreateTextureFileAttr().Set(Sdf.AssetPath(str(self._texture_path)))
                dome.CreateTextureFormatAttr().Set(UsdLux.Tokens.latlong)
            dome.CreateIntensityAttr(self._exposure * scale)
            # The sun and the moon are exposed by the *same* factor as the dome below. They are
            # quoted in lux and the dome's texture in cd/m2, so leaving the lights unexposed puts
            # the sun some two and a half decades above the sky it shares a frame with: the sky
            # renders correctly and every surface the sun touches clips to white. A sunlit 0.19
            # albedo ground and a clear zenith belong within a stop of each other, which is what
            # one exposure gives and two cannot.
            # RTX hides a dome from primary rays unless told otherwise, which gives a black
            # background lit by a sky nobody can see -- the exact failure this module fixes.
            dome.GetPrim().CreateAttribute(
                "visibleInPrimaryRay", Sdf.ValueTypeNames.Bool
            ).Set(True)
            self._orient_dome(dome, up_axis)

            self._author_body(
                stage,
                SUN_PATH,
                conditions.sun,
                up_axis,
                enabled=bool(sky.sun_enabled) and conditions.sun.is_up,
                intensity=(
                    float(
                        clear_sky_irradiance(
                            conditions.sun.elevation_deg, conditions.turbidity
                        )[0]
                    )
                    * LUMINOUS_EFFICACY_DAYLIGHT
                    * conditions.daylight
                    * self._exposure
                    * scale
                    * sun_peak
                ),
                colour=tuple(c / sun_peak for c in sun_tint),
            )
            self._author_body(
                stage,
                MOON_PATH,
                conditions.moon,
                up_axis,
                enabled=bool(sky.moon_enabled) and conditions.moon.is_up,
                # The moon's normal illuminance, from the horizontal one it produces.
                intensity=(
                    conditions.moon_lux
                    / max(math.sin(math.radians(max(conditions.moon.elevation_deg, 1.0))), 1e-3)
                    * self._exposure
                    * scale
                    * moon_peak
                ),
                colour=tuple(c / moon_peak for c in moon_tint),
            )

    @staticmethod
    def _orient_dome(dome: Any, up_axis: int) -> None:
        """Rotate the dome for a Z-up stage rather than regenerating its texture.

        The map is generated in the renderer's lat-long convention for a Y-up stage. Rotating a
        light is exact; resampling an environment map is not, and it would also mean two code
        paths producing two slightly different skies.
        """
        from pxr import Gf, UsdGeom

        xform = UsdGeom.Xformable(dome)
        xform.ClearXformOpOrder()
        if up_axis == 2:
            xform.AddRotateXOp().Set(90.0)

    @staticmethod
    def _author_body(
        stage: Any,
        path: str,
        body: Any,
        up_axis: int,
        *,
        enabled: bool,
        intensity: float,
        colour: tuple,
    ) -> None:
        from pxr import Gf, UsdGeom, UsdLux

        light = UsdLux.DistantLight.Define(stage, path)
        prim = light.GetPrim()
        if not enabled or intensity <= 0.0:
            UsdGeom.Imageable(prim).MakeInvisible()
            light.CreateIntensityAttr(0.0)
            return
        UsdGeom.Imageable(prim).MakeVisible()

        north_axis, north_sign = (2, -1.0) if up_axis == 1 else (1, 1.0)
        toward = body.direction(up_axis=up_axis, north_axis=north_axis, north_sign=north_sign)
        # A distant light emits along its own -Z, so -Z must point the way the light travels --
        # which is *away* from the body.
        rotation = Gf.Rotation(Gf.Vec3d(0.0, 0.0, -1.0), Gf.Vec3d(*(-float(v) for v in toward)))
        xform = UsdGeom.Xformable(prim)
        xform.ClearXformOpOrder()
        xform.AddOrientOp().Set(Gf.Quatf(rotation.GetQuat()))

        light.CreateIntensityAttr(float(intensity))
        light.CreateAngleAttr(float(body.angular_diameter_deg))
        light.CreateColorAttr(Gf.Vec3f(*colour))
